- backend/core-services/egov-filestore/src/main/resources/application.properties
> Feature 56: Add video supported format

- frontend/micro-ui/web/micro-ui-internals/packages/modules/im/src/components/inbox/Filter.js
> fixed health care center filter

- frontend/micro-ui/web/micro-ui-internals/packages/modules/im/src/pages/employee/CreateComplaint/index.js
> fixed dropdown issue to empty dependent fields on district change

- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/config/FileStoreConfig.java
- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/validator/StorageValidator.java
- backend/core-services/egov-filestore/src/main/resources/application.properties
> feature-57: vide size validator

- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/config/FileStoreConfig.java
- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/domain/service/StorageService.java
- backend/core-services/egov-filestore/src/main/resources/application.properties
> feature-59: validate file list size

- backend/municipal-services/im-services/README.md
- backend/municipal-services/im-services/pom.xml
- backend/municipal-services/im-services/src/main/java/org/egov/im/config/IMConfiguration.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/repository/ServiceRequestRepository.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/IMService.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/NotificationService.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/StorageService.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/WorkflowService.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/util/HRMSUtil.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/util/IMUtils.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/util/StorageUtil.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/util/UserUtils.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/validator/StorageValidator.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/web/controllers/StorageController.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/web/models/storage/StorageResponse.java
- backend/municipal-services/im-services/src/main/resources/application.properties
integrate with filestore
validate video file
code refactor
#204
> feature-204: video optimization. validation and upload

- frontend/micro-ui/web/micro-ui-internals/packages/libraries/src/services/elements/Complaint.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/im/src/pages/employee/ComplaintDetails.js
> added sendback reasons dropdown options along with sub reasons

- .github/workflows/digit-ui.yaml
- .github/workflows/im-services.yaml
Modified workflows for image build to get triggered when merged to main branch
> Added Workflow trigger for uat

- frontend/micro-ui/web/webpack.config.js
> hash bundle output for cache-busting

- .github/workflows/hrms.yaml
- backend/business-services/egov-hrms/src/main/resources/db/Dockerfile
- backend/business-services/egov-hrms/src/main/resources/db/migrate.sh
> Hrms image build

- backend/municipal-services/im-services/src/main/java/org/egov/im/consumer/NotificationConsumer.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/NotificationService.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/util/NotificationUtil.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/web/models/SendBackReason.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/web/models/Workflow.java
- backend/municipal-services/im-services/src/main/resources/application.properties
Configure sms template
Add to db
refactor
> feature-63: Sendback SMS template

- backend/municipal-services/im-services/pom.xml
- backend/municipal-services/im-services/src/main/java/org/egov/im/IMApp.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/repository/ServiceRequestRepository.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/FFMpegExecutor.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/StorageService.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/VideoService.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/util/ByteArrayMultipartFile.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/util/StorageUtil.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/util/VideoUtil.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/validator/StorageValidator.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/web/controllers/StorageController.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/web/models/ProcessingContext.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/web/models/ProcessingTimes.java
- backend/municipal-services/im-services/src/main/resources/application.properties
> feature-186: Add ffmpeg poc implementation

- backend/municipal-services/im-services/src/main/java/org/egov/im/IMApp.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/FFmpegCommandGenerator.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/FFmpegService.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/StorageService.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/VideoService.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/settings/VideoQualityConfig.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/util/DirectoryUtil.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/util/VideoUtil.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/web/models/storage/File.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/web/models/storage/StorageResponse.java
> feature-186: ffmpeg implementation

- backend/municipal-services/inbox/src/main/java/org/egov/inbox/repository/builder/V2/InboxQueryBuilder.java
> feature-141: fix

- backend/municipal-services/im-services/src/main/java/org/egov/im/config/IMConfiguration.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/repository/ServiceRequestRepository.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/FFmpegCommandGenerator.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/FFmpegService.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/StorageService.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/util/StorageUtil.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/util/VideoUtil.java
- backend/municipal-services/im-services/src/main/resources/application.properties
Add some fixes and updates for sync with filestore
> feature-187: Add ffmpeg processing

- .github/workflows/filestore.yaml
> Filestore workflow

- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/domain/service/ArtifactMapper.java
- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/repository/impl/CloudFileMgrUtils.java
> feature-186: Fix image upload issue

- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/domain/model/Artifact.java
- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/domain/service/ArtifactMapper.java
- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/persistence/repository/ArtifactRepository.java
- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/repository/impl/minio/MinioRepository.java
- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/web/controller/StorageController.java
- backend/core-services/egov-filestore/src/main/resources/application.properties
Added hack for allowing mp4 to support quicktime format
Only allow master files to be saved to database
modify get-hls endpoint to use request param
> feature-186: Add modifications for video upload

- backend/municipal-services/im-services/src/main/resources/application.properties
> ffeature-187: HLS processing

- frontend/micro-ui/web/micro-ui-internals/packages/modules/im/src/pages/employee/ComplaintDetails.js
> Added Others reject option and made comments optional for rest of the options

- backend/municipal-services/im-services/src/main/java/org/egov/im/config/AsyncConfig.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/FFmpegService.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/StorageService.java
- backend/municipal-services/im-services/src/main/resources/application.properties
> feature-187: patch

- backend/municipal-services/im-services/src/main/java/org/egov/im/config/AsyncConfig.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/FFMpegExecutor.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/FFmpegCommandGenerator.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/FFmpegService.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/StorageService.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/VideoService.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/util/StorageUtil.java
- backend/municipal-services/im-services/src/main/resources/application.properties
Temporarily removing file cleanup in tmp folder
> Feature 187

- backend/municipal-services/im-services/src/main/java/org/egov/im/util/StorageUtil.java
> feature-187: fix

- backend/municipal-services/im-services/src/main/java/org/egov/im/service/FFmpegCommandGenerator.java
> Fix FFmpegCommandGenerator.java

- backend/municipal-services/im-services/src/main/resources/application.properties
modify multipart location value to an absolute path in app properties
> Fix for multipart issue

- backend/municipal-services/im-services/src/main/java/org/egov/im/config/IMConfiguration.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/FFMpegExecutor.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/StorageService.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/VideoService.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/util/StorageUtil.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/util/VideoUtil.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/web/controllers/StorageController.java
- backend/municipal-services/im-services/src/main/resources/application.properties
Added properties
fix tmp bug issues
I made mention of an error that usually happens whenever we make new request or change files, i was able to find out why. This is due to sync and async processing. The sync process deletes the tmp file before the async starts and causes a NoFileFoundException. This is a solution
This is also due to how Springboot handles multipartFile - tomcat creates tmp files in/ tmp directory and when the process ends it deletes it, hence the reason for firstly, crerating tmp files in custom location /opt/egov/input and store as List<Files> so both sync and async can use this referene for processing
Also added some properties for ffprobe.path
> feature-187: fixes and patches

- backend/municipal-services/inbox/src/main/java/org/egov/inbox/repository/builder/V2/InboxQueryBuilder.java
- frontend/micro-ui/web/micro-ui-internals/packages/libraries/src/hooks/pgr/useInboxData.js
- frontend/micro-ui/web/micro-ui-internals/packages/libraries/src/hooks/useInboxGeneral/newFilterFn.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/im/src/components/IMCard.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/im/src/pages/employee/Inbox.js
> nearingSLA filter

- backend/municipal-services/im-services/src/main/java/org/egov/im/repository/ServiceRequestRepository.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/StorageService.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/VideoQualityProcessor.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/VideoService.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/VideoUploaderService.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/util/StorageUtil.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/util/VideoUtil.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/web/controllers/StorageController.java
- backend/municipal-services/im-services/src/main/resources/application.properties
This patch enhances user UX by psuhing at least the original chunk alongside master file before returning response
This will enable smoother experience on UI
Also, it utilizes async from end to end to speed up processing
> feature-187: optimisation and patch

- .github/workflows/digit-ui.yaml
- .github/workflows/filestore.yaml
- .github/workflows/hrms.yaml
- .github/workflows/im-services.yaml
- .github/workflows/inbox.yaml
- .github/workflows/workflow-v2.yaml
There is an Issue in workflow trigger condition.
> Workflow Changes

- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/FileStoreApplication.java
- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/config/Properties.java
- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/domain/service/ArtifactMapper.java
- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/domain/service/HLSStorageService.java
- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/domain/service/StorageService.java
- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/persistence/repository/ArtifactRepository.java
- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/repository/CloudFileManagerV2.java
- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/repository/impl/minio/MinioClientFacade.java
- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/repository/impl/minio/MinioRepository.java
- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/repository/impl/minio/MinioRepositoryV2.java
- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/utils/StorageUtil.java
- backend/core-services/egov-filestore/src/main/resources/application.properties
- backend/core-services/egov-filestore/src/test/java/org/egov/filestore/persistence/repository/ArtifactRepositoryTest.java
Add custom  tmp file implementation
Add async for video uploads
Use try-resource where necessary to close used resources gracefully
> Feature 186: Filestore HLS re-implementation

- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/repository/impl/minio/MinioRepositoryV2.java
- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/web/controller/StorageController.java
ContentType is null on dev
Resolved contentType via multipartfile
> feature-186: patch

- backend/municipal-services/im-services/src/main/java/org/egov/im/config/IMConfiguration.java
- backend/municipal-services/im-services/src/main/java/org/egov/im/service/NotificationService.java
- backend/municipal-services/im-services/src/main/resources/application.properties
Add SMS template to db
Add SMS template resolution
> feature-179: Feedback SMS change

- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/persistence/repository/ArtifactRepository.java
- backend/core-services/egov-filestore/src/main/java/org/egov/filestore/repository/impl/minio/MinioRepositoryV2.java
the master.m3u8 file path stored in database is malformed,
this patch resolves master.m3u8 path in db
> feature-186: patch and fix

- .github/workflows/assam-ui.yaml
- .github/workflows/digit-ui.yaml
- .github/workflows/filestore.yaml
- .github/workflows/im-services.yaml
- .github/workflows/inbox.yaml
- .github/workflows/manipur-ui.yaml
- .github/workflows/meghalaya-ui.yaml
- .github/workflows/mizoram-ui.yaml
- .github/workflows/nagaland.yaml
- .github/workflows/odisha-ui.yaml
- .github/workflows/sikkim-ui.yaml
- .github/workflows/workflow-v2.yaml
> DevOps 420

- backend/municipal-services/inbox/src/main/java/org/egov/inbox/service/V2/InboxServiceV2.java
- backend/municipal-services/inbox/src/main/resources/application.properties
#438 
if a vendor requests for state level tenantId tickets, instead of wildcard we request the specific tenants they have availability to
> limit vendor users to fetch only assigned tenant tickets

- .github/workflows/assam-ui.yaml
- .github/workflows/manipur-ui.yaml
- .github/workflows/meghalaya-ui.yaml
- .github/workflows/mizoram-ui.yaml
- .github/workflows/nagaland.yaml
- .github/workflows/odisha-ui.yaml
- .github/workflows/sikkim-ui.yaml
- frontend/micro-ui/web/docker/nginx.conf
Modify endpoint from /state-ui to /state
> DevOps 446

- .github/workflows/assam-ui.yaml
- .github/workflows/manipur-ui.yaml
- .github/workflows/meghalaya-ui.yaml
- .github/workflows/mizoram-ui.yaml
- .github/workflows/nagaland.yaml
- .github/workflows/odisha-ui.yaml
- .github/workflows/sikkim-ui.yaml
- frontend/micro-ui/web/docker/nginx.conf
> DevOps 446 (#447)

- .github/workflows/assam-ui.yaml
- .github/workflows/gujarat-ui.yaml
- .github/workflows/manipur-ui.yaml
- .github/workflows/meghalaya-ui.yaml
- .github/workflows/mizoram-ui.yaml
- .github/workflows/nagaland.yaml
- .github/workflows/sikkim-ui.yaml
- frontend/micro-ui/web/docker/Dockerfile
(cherry picked from commit 4ba7cb3b01cb4922ebbfffcd6ddb0fa8e5cdac42)
> Gujarat UI image (#461)

- .github/workflows/asset-registry.yaml
> DevOps 668

- backend/e4h-services/vendor-registry/pom.xml
Remove opentelemetry bom-alpha:2.1.0-alpha dependency
> Remove opentelemetry alpha dependency

- frontend/micro-ui/web/micro-ui-internals/packages/libraries/src/hooks/pgr/useInboxData.js
- frontend/micro-ui/web/micro-ui-internals/packages/libraries/src/hooks/useInboxGeneral/useNewInbox.js
1.  Removed Unnecessary Trigger Mechanism
File: frontend/micro-ui/web/micro-ui-internals/packages/libraries/src/hooks/useInboxGeneral/useNewInbox.js
Problem: The hook had a useEffect that ran on every component mount and set a unique timestamp trigger
Solution: Removed the useState trigger, useEffect, and the trigger from the React Query key array
2. Added Better Caching Configuration
Added React Query optimizations:
staleTime: 30000 - Consider data fresh for 30 seconds
cacheTime: 300000 - Keep in cache for 5 minutes
refetchOnWindowFocus: false - Prevent refetch on window focus
refetchOnMount: false - Prevent refetch on component mount if data exists
> Fixes the multiple call issue on the Inbox

- backend/e4h-services/processor-services/src/main/java/org/egov/processor/service/impl/StorageServiceImpl.java
- backend/e4h-services/processor-services/src/main/java/org/egov/processor/service/impl/VideoServiceImpl.java
- backend/e4h-services/processor-services/src/main/java/org/egov/processor/utils/StorageUtil.java
the methods are ending early and is causing kafka to flush messages before actually processing files
> remove async parts as kafka gets wrong message

- backend/core-services/egov-workflow-v2/src/main/java/org/egov/wf/service/EnrichmentService.java
This reverts commit 3be9e05f3fce31e92aebbad6ff9a57bb25340049.
> Revert "Update Null checks in EnrichmentService (#993)"

- .github/workflows/assam-ui.yaml
- .github/workflows/asset-registry.yaml
- .github/workflows/boundary-service.yaml
- .github/workflows/digit-ui.yaml
- .github/workflows/facility-registry.yaml
- .github/workflows/filestore.yaml
- .github/workflows/gujarat-ui.yaml
- .github/workflows/hrms.yaml
- .github/workflows/im-services-analytics.yaml
- .github/workflows/im-services.yaml
- .github/workflows/inbox.yaml
- .github/workflows/manipur-ui.yaml
- .github/workflows/meghalaya-ui.yaml
- .github/workflows/mizoram-ui.yaml
- .github/workflows/nagaland.yaml
- .github/workflows/odisha-ui.yaml
- .github/workflows/processor-service.yaml
- .github/workflows/project-service.yaml
- .github/workflows/sikkim-ui.yaml
- .github/workflows/vendor-Registry.yaml
- .github/workflows/workflow-v2.yaml
- build/maven/Dockerfile
Git Ticket: https://github.com/Selco-Foundation/E4H_Digital_Platform/issues/1039
> DevOps:1039- Reduce Docker image build time

- backend/e4h-services/im-services-analytics/src/main/java/org/selco/e4h/service/PrioritySLAService.java
- backend/e4h-services/im-services-analytics/src/main/java/org/selco/e4h/service/UpdateService.java
Fix issue on sla remaining value
> Fix issue on Defined Total SLA value

- frontend/micro-ui/web/micro-ui-internals/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/css/package.json
- frontend/micro-ui/web/micro-ui-internals/packages/css/src/components/tag.scss
- frontend/micro-ui/web/micro-ui-internals/packages/libraries/src/hooks/pgr/useInboxData.js
- frontend/micro-ui/web/micro-ui-internals/packages/libraries/src/hooks/useInboxGeneral/newFilterFn.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/im/src/components/inbox/Filter.js
- frontend/micro-ui/web/public/index.html
> Sprint 10 UI changes

- frontend/micro-ui/web/micro-ui-internals/packages/libraries/src/utils/fileType.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/ChangeCity.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/citizen/Home/UserProfile.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/im/src/components/MobileInbox.js
- frontend/micro-ui/web/micro-ui-internals/packages/react-components/src/atoms/DisplayPhotos.js
- frontend/micro-ui/web/micro-ui-internals/packages/react-components/src/atoms/Dropdown.js
Fixed pending IM module bugs from sprint 10.
- Changed navbar tenant id dropdown styling
- Resolved mobile inbox health care centre name localization
- Fixed health care center not displaying selected tenant in profile page
closes #910 
closes #1222 
fixes #1223
> [Fix]: Sprint 10 fixes

- backend/e4h-services/ingestion-service/app/api/endpoints/file_ingestion.py
https://github.com/Selco-Foundation/E4H_Digital_Platform/issues/1144
> flag_for_qc api

- frontend/micro-ui/web/micro-ui-internals/packages/libraries/src/utils/Analytics/gtag.js
removed the loadGA function with correct flush call
> google analytics fix

- frontend/micro-ui/web/micro-ui-internals/packages/libraries/src/utils/Analytics/baseParams.js
- frontend/micro-ui/web/micro-ui-internals/packages/libraries/src/utils/Analytics/context.js
- frontend/micro-ui/web/micro-ui-internals/packages/libraries/src/utils/Analytics/track.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/Login/login.js
Fixed the browser name issue 
Added Facility name 
Added State name
> GA4 bug fixes and state addition

- .github/workflows/im-services.yaml
- backend/e4h-services/im-services/src/main/resources/db/Dockerfile
- backend/e4h-services/im-services/src/main/resources/db/migrate.sh
- backend/e4h-services/im-services/src/main/resources/db/migration/main/V20250903133200__delete_dummy_tickets.sql
- Implemented java based sql migrations
> Deletion of Dummy tickets

- frontend/installation-ui/web/micro-ui-internals/packages/modules/pm/src/hooks/useProject.js
- frontend/installation-ui/web/micro-ui-internals/packages/modules/pm/src/pages/employee/ProjectTable.js
- frontend/installation-ui/web/micro-ui-internals/packages/modules/pm/src/services/Project.js
> implemented fetch endpoint

- backend/e4h-services/im-services/src/main/resources/db/migration/main/V20250918123200__correct_Othertfans.sql
added flyway migration file to edit issue subType of already created tickets to 'OtherFan' from 'OthertFan'
> FIX: add migration to correct spelling of subtype 'OtherFan'

- backend/e4h-services/ingestion-service/app/api/endpoints/file_ingestion.py
- backend/e4h-services/ingestion-service/app/utils/facility_validator.py
On upload unlink already linked facilities if marked as no in "Include in Project" column
> added facility unlinking on template upload

- frontend/micro-ui/web/micro-ui-internals/packages/libraries/src/hooks/pgr/useComplaintDetails.js
This reverts commit 7419812058020f9b8adf1fac5e32da01500db8ed.
> [REFACTOR]: Revert "Fixed casing issue for health care center type in ticket details page (#1145)"

- frontend/micro-ui/web/micro-ui-internals/packages/libraries/src/hooks/pgr/useComplaintDetails.js
This reverts commit 7419812058020f9b8adf1fac5e32da01500db8ed
> [REVERT]: "Fixed casing issue for health care center type in ticket details page (#1145)" (#1488)

- frontend/installation-ui/web/micro-ui-internals/example/src/setupProxy.js
- frontend/installation-ui/web/micro-ui-internals/packages/css/package.json
- frontend/installation-ui/web/micro-ui-internals/packages/css/src/components/popup.scss
- frontend/installation-ui/web/micro-ui-internals/packages/css/src/index.scss
- frontend/installation-ui/web/micro-ui-internals/packages/css/src/pages/employee/activitydetailstable.scss
- frontend/installation-ui/web/micro-ui-internals/packages/modules/pm/src/Module.js
- frontend/installation-ui/web/micro-ui-internals/packages/modules/pm/src/components/CreateFieldPlan/ActivityDetails.js
- frontend/installation-ui/web/micro-ui-internals/packages/modules/pm/src/components/CreateFieldPlan/OrganizationUserDropdown.js
- frontend/installation-ui/web/micro-ui-internals/packages/modules/pm/src/components/Custom/CustomDropdown.js
- frontend/installation-ui/web/micro-ui-internals/packages/modules/pm/src/components/FormComposer/ActivitySelector.js
- frontend/installation-ui/web/micro-ui-internals/packages/modules/pm/src/hooks/useActivityAssignment.js
- frontend/installation-ui/web/micro-ui-internals/packages/modules/pm/src/hooks/useFieldPlan.js
- frontend/installation-ui/web/micro-ui-internals/packages/modules/pm/src/hooks/useOrganization.js
- frontend/installation-ui/web/micro-ui-internals/packages/modules/pm/src/hooks/useOrganizationUser.js
- frontend/installation-ui/web/micro-ui-internals/packages/modules/pm/src/pages/employee/CreateFieldPlan.js
- frontend/installation-ui/web/micro-ui-internals/packages/modules/pm/src/pages/employee/CreateProject.js
- frontend/installation-ui/web/micro-ui-internals/packages/modules/pm/src/pages/employee/ProjectFieldPlans.js
- frontend/installation-ui/web/micro-ui-internals/packages/modules/pm/src/pages/employee/Response.js
- frontend/installation-ui/web/micro-ui-internals/packages/modules/pm/src/services/Activity.js
- frontend/installation-ui/web/micro-ui-internals/packages/modules/pm/src/services/FieldPlan.js
- frontend/installation-ui/web/micro-ui-internals/packages/modules/pm/src/services/Ingestion.js
- frontend/installation-ui/web/micro-ui-internals/packages/modules/pm/src/services/PMService.js
- frontend/installation-ui/web/micro-ui-internals/packages/modules/pm/src/services/Project.js
- frontend/installation-ui/web/micro-ui-internals/packages/modules/pm/src/services/Vendor.js
- frontend/installation-ui/web/public/index.html
* Integrated field plans search api in project field plans page
* Integrated field plan create and update api calls
* Integrated field plan facility data apis
* Added project id in payload for project facility data validation api call
* Added activity details page UI
* Activity details page removal options refactorings
* Integrated MDMS, Organization apis into activity details
* Integrated activity assign api
* Integrated activity assignment search api
* Added activity assignment update and delete apis
* Added project status update api
* Activity details page refactoring
* CSSv1.0.7
* Restricted edits to field plan data which is not in draft status
* Integrated activity assignment edit api
* Custom dropdown implementation and ui bug fixes
* Code rabbit changes
* CSSv1.0.8
> [FEATURE]: Project Manager UI - Field Plan Creation (#1485)
